name: ff
description: e-tron-frontend

# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.3.2"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  cloud_firestore: ^4.2.0
  responsive_scaffold_nullsafe: ^1.0.1
  intl: ^0.17.0
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/factories/