// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC5ouIE2CXGFmCMDffY9MOzRLNfWzk-7U',
    appId: '1:635296622270:web:5d7c3a2a5e4347b5b060ef',
    messagingSenderId: '635296622270',
    projectId: 'e-tron-7a216',
    authDomain: 'e-tron-7a216.firebaseapp.com',
    databaseURL: 'https://e-tron-7a216.firebaseio.com',
    storageBucket: 'e-tron-7a216.appspot.com',
    measurementId: 'G-Z85E3C9W9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCADU82Pla6OiJbpxojao_AOfYMZE0IqZw',
    appId: '1:635296622270:android:15263ceab271d789b060ef',
    messagingSenderId: '635296622270',
    projectId: 'e-tron-7a216',
    databaseURL: 'https://e-tron-7a216.firebaseio.com',
    storageBucket: 'e-tron-7a216.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU-PZQyse7PpCGPvi4v79d9u2ko74hanc',
    appId: '1:635296622270:ios:8c098f5395931d39b060ef',
    messagingSenderId: '635296622270',
    projectId: 'e-tron-7a216',
    databaseURL: 'https://e-tron-7a216.firebaseio.com',
    storageBucket: 'e-tron-7a216.appspot.com',
    iosClientId: '635296622270-hkosor88c0qb9575sqaqgolfjafe8h2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.ff',
  );
}
